update readme
rust-fuzz/afl.rs pull request #366
Opened 2023-08-10 09:01 UTC by vanhauser-thc

small addition to help people to use afl.rs more effectively.

also note I just released afl++ 4.08c :)

2023-08-10 23:59 UTC, smoelius requested changes
Thank you very much for this.

All of my suggestions are very nitpicky, and mostly about reducing the number words.

Though, may I please ask that this section be positioned between the "What does it look like?" and "`lazy_static` variables" sections? (I am trying be respectful of the previous maintainers' content.)

I will publish a new version with these changes and afl++ 4.08c within a day or so.

2023-08-10 23:59 UTC, smoelius commented on README.md
> +By default the AFL++ CMPLOG feature is activated, which is an amazing feature to achieve good code coverage.
```suggestion
By default, the AFL++ [CMPLOG](https://github.com/AFLplusplus/AFLplusplus/blob/stable/instrumentation/README.cmplog.md) feature is activated, which helps to achieve good code coverage.
```

2023-08-10 23:59 UTC, smoelius commented on README.md
> +However it is not beneficial to activate CMPLOG on more than 2 instances.
```suggestion
However, it is not beneficial to activate CMPLOG on more than two instances.
```

2023-08-10 23:59 UTC, smoelius commented on README.md
> +It is highly recommended to familiarize yourself with the AFL++ features and how to successfully run a fuzzing campaign. This [document](https://github.com/AFLplusplus/AFLplusplus/blob/stable/docs/fu
```suggestion
This [document](https://github.com/AFLplusplus/AFLplusplus/blob/stable/docs/fuzzing_in_depth.md) will familiarize you with AFL++ features to help in running a successful fuzzing campaign.
```

2023-08-11 09:27 UTC, vanhauser-thc commented
sure, no problem!
is it fine now?

2023-08-11 09:57 UTC, smoelius approved these changes

2023-08-11 09:58 UTC, smoelius commented
Yes! Thanks tremendously!

2023-08-11 09:58 UTC, merged